"""added status flags and cascade deletes

Revision ID: 027f42b76807
Revises: c9a24f2d35d8
Create Date: 2026-02-10 12:38:41.040344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '027f42b76807'
down_revision: Union[str, Sequence[str], None] = 'c9a24f2d35d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('status', sa.String(), nullable=True))
    op.add_column('events', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'status')
    op.drop_column('bookings', 'status')
    # ### end Alembic commands ###
